# Generated by Django 6.0.1 on 2026-01-30 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="subscribed_journalists",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="subscribed_publishers",
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscriptions_journalists",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscriptions_publishers",
            field=models.ManyToManyField(blank=True, to="news.publisher"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="articles",
            field=models.ManyToManyField(related_name="newsletters", to="news.article"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                related_name="publisher_editors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="journalists",
            field=models.ManyToManyField(
                blank=True,
                related_name="publisher_journalists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
