# Generated by Django 6.0.1 on 2026-02-06 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_remove_customuser_subscribed_journalists_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublisherRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "journalist",
                    models.ForeignKey(
                        limit_choices_to={"role": "journalist"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliation_requests",
                        to="news.publisher",
                    ),
                ),
            ],
            options={
                "unique_together": {("journalist", "publisher")},
            },
        ),
    ]
